version: '3.8'

services:
  django:
    build: .  # Builds from the current directory
    container_name: django_backend
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]  # The entrypoint script will handle migrations and collectstatic
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - minio
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: storage
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"    # MinIO access port
      - "9001:9001"    # MinIO console UI
    environment:
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - backend

volumes:
  mongo_data:
  minio_data:

networks:
  backend:
