name: CI/CD for Docker on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repository structure (debugging)
        run: ls -R

      - name: Install sshpass and Docker
        run: sudo apt-get install sshpass && sudo snap install docker

      - name: Ensure target directory exists on Droplet
        run: |
          sshpass -p "${{ secrets.DO_ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@137.184.86.31 "
          mkdir -p ~/FileNest/backend && ls -l ~/FileNest
          "

      - name: Copy files to Droplet using SCP with password
        run: |
          sshpass -p "${{ secrets.DO_ROOT_PASSWORD }}" scp -r -o StrictHostKeyChecking=no /FileNest/backend root@137.184.86.31:~/FileNest/

      # To-Do: Add frontend job later

      - name: Deploy containers on DigitalOcean Droplet
        run: |
          sshpass -p "${{ secrets.DO_ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@137.184.86.31 "
          cd ~/FileNest/backend &&
          docker-compose down || true &&
          docker-compose up --build
          "
