name: CI/CD for Docker on DigitalOCean

on:
  push:
    branches:
      - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up SSH
     uses: webfactory/ssh-agent@v0.5.3
     with:
      ssh-private-key: ${{ secrets.DO_SSH_KEY }}

   - name: Copy files to Droplet
     run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@157.245.11.124:/

   - name: Deploy containers on DigitalOcean Droplet
     run: |
          ssh -o StrictHostKeyChecking=no root@157.245.11.124 "
          cd /path/to/your/project &&
          docker-compose down || true &&
          docker-compose up -d --build
          "