name: CI/CD for Docker on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy files to Droplet using SCP with password
        run: |
          sshpass -p "${{ secrets.DO_ROOT_PASSWORD }}" scp -r -o StrictHostKeyChecking=no ./ root@137.184.86.31:/

      - name: Deploy containers on DigitalOcean Droplet
        run: |
          sshpass -p "${{ secrets.DO_ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@137.184.86.31 "
            cd /path/to/your/project &&
            docker-compose down || true &&
            docker-compose up -d --build
          "
